language: node_js
node_js:
- '6'
env:
  matrix:
  - TRAVIS_NODE_VERSION="6.3"
before_script:
- webpack
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAILFVX7VJZDRQK3IQ"
  secret_access_key:
    secure: "PlnfAv66LSS5MnXVIi/nks7zdzO5zRSQily/2pneM6UcYnx1gV/kB12WwyTVesLthDP1tG8petb//IzZCQsiItlVcEreU4k43QAFTuM9J/hCgTrmHvOm4SFJn4NzkeMHsDp8zZPzStzbn95D3tIQIV/udsCn5luFY8VPy31z8KIWZJdpAoT4yackQJ3iownWeFuPOtRVA1Lp6TzPY1OYjZFrwp5plBW760g8oucZUMDJ/meiGcX2I3O1Hti1TkPMb1TccN9K7QkIRT1SbPdJCqYifJ5Sn7hlmVxDZyeabke7jM9oC3/fSSpEIneL4zCFIS98wqdl9V4a0j+REhDg320Lq3CN6SG4vYJwyxieql5+mP8Qp1H90LvNc4+8SK5PBzJRXjBfxxP+br9ULonbydrW4y/+6r7J79qplCOA/fx+rHNqPKY2nLEq4d6JE+j0j2JWiN0SwKH4iGP3s6WzG9CAgX72L1hm0wpB/6n+SkgGCJ8DAmfATaiIEgGYEd2uwFWNOuQ6vuAvJRk7L4YG5eErfO0x4uO/cOzcWVEURv7I4iucFV2+ws/laY0Ta4dNpr9mbJe/EBYeZSdHsW8Dax8UXgWH2GaychfjhsYdfV5eEIiNlQlDnIdAfE6edE2JDDOufDJTlydq2ODOTsu83/kUQ8MtOu8SPhdU7cFzySA="
  region: us-east-2
  app: flickpick
  env: ee-tsqktm6kwz
  bucket_name: elasticbeanstalk-us-east-2-088432678416
