language: node_js
node_js:
- '6'
env:
  matrix:
  - TRAVIS_NODE_VERSION="6.3"
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIPKLFWX5TZYVHIFA
  secret_access_key:
    secure: jmO38Xj2vGTaUHKFQpYBEtLiCy3HoYiYYKqInM+dHzNoBQK+frVcjxEhczGHq6BMY+596ken4iDi0jaXs3lZqlig0LZs76h1d6JTTcOnGq129SJaIeQIRFtFFE6VlgkJY1CeAR1ymGhR37rGu6314Pzm3IlLHnbcjqLNPJ177aWgWGBSe7aMr5lcZKz4B1/quwBe0L4H5j5f7WNrBNaFUKmRg8gQXBLzm/t8ZfxAWhxpz9ZuFXuxjBOfLfNYj9BDTZki+3sg9dVI7AmmoxLxsUorDLRtCK5akgIv9Qoqy0425LexA/5quolCP2y7X9nLzLdW3nt/owZo9LUo3solVt7dmtX4EJPOzfqqEUnxwOI5XjcdIr/kYjB9UznIbkBgJXRNl3Tw4KvOQ40iAT1+DT4UlYGmNG6stb7HczaVindsqgOp16oA1H4wFOVGfU4b88fLsRLArgStj5+s/f56ql6hc1g4CEXGts7ULIqQCqO4jZeie0lN9GeCRHtXo3p4orNeeZvBhREkVtdcqix0tEK4429pnuouuxngFyNJ941SnR4QvdL1M+vQMXjVnIvQAcTZpS1jh0Owomj/N0DpZNi/+k3aUnrRkJxEHPkecSptRBWj3zcPBLkub0+TBdcP9kFLFBCcONY/lYtZGZeAVzAopTNtbgMsfmwi/F6FwkY=
  region: us-east-2
  app: flickpick
  env: fliq
  bucket_name: elasticbeanstalk-us-east-2-088432678416
  on:
    repo: binary100/fliq
    branch: dev
